/**
 * OpportunityCard — read-only display of the structured opportunity card
 * generated by the Idea Lab. Renders in both server (account detail) and
 * client (Idea Lab result) contexts, so it has no `'use client'` directive.
 */

import type { OpportunityCard } from '@/lib/types/opportunity'

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <dt className="font-sans text-xs font-bold uppercase tracking-wider text-neutral-500 dark:text-neutral-400">
        {label}
      </dt>
      <dd className="mt-1 text-sm text-neutral-800 dark:text-neutral-200">{children}</dd>
    </div>
  )
}

function List({ items }: { items: string[] }) {
  if (!items || items.length === 0) {
    return <span className="text-neutral-400">—</span>
  }
  return (
    <ul className="space-y-1">
      {items.map((item, i) => (
        <li key={`${item.slice(0, 24)}-${i}`} className="flex gap-2 text-sm">
          <span aria-hidden="true" className="text-brand-red">
            &rsaquo;
          </span>
          <span>{item}</span>
        </li>
      ))}
    </ul>
  )
}

const currency = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  maximumFractionDigits: 0,
})

const number = new Intl.NumberFormat('en-US')

export function OpportunityCardView({ card }: { card: OpportunityCard }) {
  return (
    <article className="rounded-lg border border-neutral-200 bg-white p-6 shadow-sm dark:border-neutral-800 dark:bg-neutral-900">
      <header className="border-b border-neutral-200 pb-4 dark:border-neutral-800">
        <div className="flex flex-wrap items-center gap-2">
          <span className="font-sans text-xs font-semibold uppercase tracking-wider text-brand-blue">
            {card.businessFunction}
          </span>
          <span className="font-sans text-xs text-neutral-400">&middot;</span>
          <span className="font-sans text-xs text-neutral-500 dark:text-neutral-400">
            {card.industry}
          </span>
          <span className="font-sans text-xs text-neutral-400">&middot;</span>
          <span className="font-sans text-xs text-neutral-500 dark:text-neutral-400">
            {card.complexity} complexity
          </span>
        </div>
        <h2 className="mt-2 font-headline text-2xl font-bold leading-snug">{card.title}</h2>
        <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-300">
          {card.proposedAgenticSolution}
        </p>
      </header>

      <dl className="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-2">
        <Field label="Problem">{card.problem}</Field>
        <Field label="Current process">{card.currentProcess}</Field>
        <Field label="Proposed agentic solution">{card.proposedAgenticSolution}</Field>
        <Field label="Automation pattern">{card.automationPattern}</Field>
        <Field label="Systems">
          {card.systems.length > 0 ? card.systems.join(', ') : '—'}
        </Field>
        <Field label="Automation potential">
          <span className="font-semibold">{card.automationPotential}%</span>
        </Field>
        <Field label="Annual volume">
          {card.annualVolume > 0 ? `${number.format(card.annualVolume)} units` : '—'}
        </Field>
        <Field label="Current annual effort">
          {card.currentAnnualEffort > 0
            ? `${number.format(card.currentAnnualEffort)} hrs/yr`
            : '—'}
        </Field>
        <Field label="Estimated automatable hours">
          {number.format(card.estimatedAutomatableHours)} hrs/yr
        </Field>
        <Field label="Estimated capacity value">
          {currency.format(card.estimatedCapacityValue)}/yr
        </Field>
        <Field label="Potential financial benefits">
          {currency.format(card.potentialFinancialBenefits)}/yr
        </Field>
      </dl>

      <div className="mt-6 grid grid-cols-1 gap-5 sm:grid-cols-2">
        <div>
          <h3 className="font-sans text-xs font-bold uppercase tracking-wider text-neutral-500 dark:text-neutral-400">
            Risks
          </h3>
          <div className="mt-2">
            <List items={card.risks} />
          </div>
        </div>
        <div>
          <h3 className="font-sans text-xs font-bold uppercase tracking-wider text-neutral-500 dark:text-neutral-400">
            Required controls
          </h3>
          <div className="mt-2">
            <List items={card.requiredControls} />
          </div>
        </div>
        <div>
          <h3 className="font-sans text-xs font-bold uppercase tracking-wider text-neutral-500 dark:text-neutral-400">
            Assumptions
          </h3>
          <div className="mt-2">
            <List items={card.assumptions} />
          </div>
        </div>
        <div>
          <h3 className="font-sans text-xs font-bold uppercase tracking-wider text-neutral-500 dark:text-neutral-400">
            Next steps
          </h3>
          <div className="mt-2">
            <List items={card.nextSteps} />
          </div>
        </div>
      </div>
    </article>
  )
}
